Project 1/force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mails</relationshipLabel>
    <relationshipName>Mails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Project 1/force-app/main/default/objects/Mail__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <formula>Inhabitant__r.Address__r.Street__c + &apos;, &apos; + Inhabitant__r.Address__r.City__c + &apos; &apos; +  TEXT(Inhabitant__r.Address__r.State__c) + &apos; &apos; +  Inhabitant__r.Address__r.Zip_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mailing Address</label>
    <type>Text</type>
</CustomField>

Project 1/force-app/main/default/classes/MailControllerExtension.cls
public class MailControllerExtension {
    //constructor
    public MailControllerExtension(ApexPages.StandardSetController sc){
        
    }
    
    //Define our variables
    public List<Mail__c> mailList{get;set;}
    public String statusOptions{get;set;}

    public String recordID {get; set; }


    //Get In transit, Delivered, or All packages
    public void getMail() {
        if(StatusOptions == 'In Transit'){
            mailList = new List<Mail__c>([SELECT Id, Inhabitant__c, Mailing_Address__c, Insurance__c, Value__c, Delivered__c FROM Mail__c WHERE Delivered__c = false AND OwnerID=:userInfo.getUserId()]);
        }else if(statusOptions == 'Delivered'){
            mailList = new List<Mail__c>([SELECT Id, Inhabitant__c, Mailing_Address__c, Insurance__c, Value__c, Delivered__c FROM Mail__c WHERE Delivered__c = true AND OwnerID=:userInfo.getUserId()]);
        }else{
            mailList = new List<Mail__c>([SELECT Id, Inhabitant__c, Mailing_Address__c, Insurance__c, Value__c, Delivered__c FROM Mail__c WHERE OwnerID=:userInfo.getUserId()]);
        }    
    }

    public PageReference redirect() {
        PageReference result = Page.CustomSearchPackageView;
        result.getParameters().put('recordID', recordID);
        result.setRedirect(true);
        return result;
    }

    //Redirect to Custom Search Package View page
    public Pagereference redirectSearchPage() {
        return Page.CustomSearchPackageView;
    }
}